plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
//    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_name
}

// Mojang ships Java 17 to end users in 1.18+, so your mod should target Java 17.
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    runs {
        // applies to all the run configs below
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'info'
            property 'mixin.env.remapRefMap','true'
            property 'mixin.env.refMapRemappingFile', "${project.projectDir}/build/createSrgToMcp/output.srg"
            arg "-mixin.config=endless.mixins.json"
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }
        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            // example of overriding the workingDirectory set in configureEach above
            workingDirectory project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url 'https://maven.aliyun.com/repository/public/' }
    maven { url 'https://maven.aliyun.com/repository/gradle-plugin/' }
    maven { url 'https://maven.aliyun.com/repository/forge/' }
    maven { url 'https://maven.aliyun.com/repository/central/' }

    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven { url 'https://maven.blamejared.com' }
    maven {
        name = "Curios"
        url = uri("https://maven.theillusivec4.top/")
    }
    maven {
        name = 'Favouriteless Maven'
        url 'https://maven.favouriteless.net/releases'
    }
    maven { url = "https://maven.createmod.net" } // Ponder, Flywheel
    maven { url 'https://maven.covers1624.net/' }
    maven { url "https://maven.shedaniel.me/" }
    // flatDir {
    //     dir 'libs'
    // }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    implementation fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
    compileOnly fg.deobf("curse.maven:jade-324717:${jade_id}")
    compileOnly fg.deobf("curse.maven:curios-309927:${curios_id}")

//    compileOnly fg.deobf("curse.maven:re-avaritia-623969:${ra_id}")
    compileOnly fg.deobf("vazkii.botania:Botania:${minecraft_version}-${bot_ver}")
    compileOnly fg.deobf("curse.maven:blood-magic-224791:${bloodmagic_id}")
    compileOnly fg.deobf("curse.maven:enchanted-witchcraft-560363:${enchanted_id}")
    compileOnly fg.deobf("curse.maven:draconic-evolution-223565:${de_id}")
    compileOnly fg.deobf("curse.maven:crafttweaker-239197:${crt_id}")
    compileOnly fg.deobf("curse.maven:projecte-226410:${pe_id}")
    compileOnly fg.deobf("vazkii.botania:Botania:${minecraft_version}-${bot_ver}")
    compileOnly fg.deobf("curse.maven:ice-and-fire-dragons-264231:${iaf_id}")
    compileOnly fg.deobf("curse.maven:create-328085:${create_id}")
    compileOnly fg.deobf("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_id}")
    compileOnly fg.deobf("com.teamcofh:thermal_core:${minecraft_version}-${thermal_core_version}+")
    compileOnly fg.deobf("curse.maven:cofh-core-69162:${cofh_core_id}")
    compileOnly fg.deobf("curse.maven:thermal-foundation-222880:${thermal_id}")
    compileOnly fg.deobf("curse.maven:mantle-74924:${mantle_id}")
    compileOnly fg.deobf("curse.maven:tinkers-construct-74072:${tc3_id}")
    compileOnly fg.deobf("curse.maven:yuoenchants-698171:${ye_id}")
    compileOnly fg.deobf("curse.maven:applied-energistics-2-223794:${ae2_id}")
    compileOnly fg.deobf("curse.maven:the-twilight-forest-227639:${ttf_id}")
    compileOnly fg.deobf("curse.maven:slashblade-resharped-1022428:${sb_re_id}")
    compileOnly fg.deobf("curse.maven:croparia-250235:${croparia_id}")
    compileOnly fg.deobf("curse.maven:refined-storage-243076:${rs_id}")
    compileOnly fg.deobf("curse.maven:touhou-little-maid-355044:${tlm_id}")
    compileOnly fg.deobf("me.shedaniel.cloth:cloth-config-forge:${cc_api_ver}")
    compileOnly fg.deobf("curse.maven:spacearms-698166:${spacearms_id}")

    runtimeOnly fg.deobf("curse.maven:jade-324717:${jade_id}")
    runtimeOnly fg.deobf("curse.maven:selene-499980:4806893")
    runtimeOnly fg.deobf("curse.maven:mmmmmmmmmmmm-225738:${mmmm_id}")
    runtimeOnly fg.deobf("curse.maven:curios-309927:${curios_id}")
    runtimeOnly fg.deobf("curse.maven:crafttweaker-239197:${crt_id}")
    runtimeOnly fg.deobf("curse.maven:touhou-little-maid-355044:${tlm_id}")
    runtimeOnly fg.deobf("me.shedaniel.cloth:cloth-config-forge:${cc_api_ver}")
    runtimeOnly fg.deobf("curse.maven:spacearms-698166:${spacearms_id}")
    runtimeOnly fg.deobf("curse.maven:kaguyafd-1449092:${kfd_id}")

//    runtimeOnly fg.deobf("curse.maven:re-avaritia-623969:${ra_id}")
    runtimeOnly fg.deobf("curse.maven:projecte-226410:${pe_id}")
    runtimeOnly fg.deobf("vazkii.patchouli:Patchouli:${minecraft_version}-${patchouli_ver}")
//    runtimeOnly fg.deobf("vazkii.botania:Botania:${minecraft_version}-${bot_ver}")
//    runtimeOnly fg.deobf("curse.maven:blood-magic-224791:${bloodmagic_id}")
//    runtimeOnly fg.deobf("curse.maven:enchanted-witchcraft-560363:${enchanted_id}")
    runtimeOnly fg.deobf("curse.maven:codechicken-lib-1-8-242818:${ccl_id}")
    runtimeOnly fg.deobf("curse.maven:brandons-core-231382:${bc_id}")
    runtimeOnly fg.deobf("curse.maven:draconic-evolution-223565:${de_id}")

//    runtimeOnly fg.deobf("curse.maven:citadel-331936:${citadel_id}")
//    runtimeOnly fg.deobf("curse.maven:ice-and-fire-dragons-264231:${iaf_id}")
//    runtimeOnly fg.deobf("curse.maven:create-328085:${create_id}")
//    runtimeOnly fg.deobf("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_id}")
//    runtimeOnly fg.deobf("com.teamcofh:thermal_core:${minecraft_version}-${thermal_core_version}+")
//    runtimeOnly fg.deobf("curse.maven:cofh-core-69162:${cofh_core_id}")
//    runtimeOnly fg.deobf("curse.maven:thermal-foundation-222880:${thermal_id}")
//    runtimeOnly fg.deobf("curse.maven:thermal-cultivation-271835:${thermal_c_id}")
//    runtimeOnly fg.deobf("curse.maven:mantle-74924:${mantle_id}")
//    runtimeOnly fg.deobf("curse.maven:tinkers-construct-74072:${tc3_id}")
//    runtimeOnly fg.deobf("curse.maven:yuoenchants-698171:${ye_id}")
//    runtimeOnly fg.deobf("curse.maven:guideme-1173950:${guideme_id}")
//    runtimeOnly fg.deobf("curse.maven:applied-energistics-2-223794:${ae2_id}")
//    runtimeOnly fg.deobf("curse.maven:the-twilight-forest-227639:${ttf_id}")
//    runtimeOnly fg.deobf("curse.maven:slashblade-resharped-1022428:${sb_re_id}")
//    runtimeOnly fg.deobf("curse.maven:croparia-250235:${croparia_id}")
//    runtimeOnly fg.deobf("curse.maven:refined-storage-243076:${rs_id}")

    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

// Example for how to get properties into the manifest for reading at runtime.
tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1', // We are version 1 of ourselves
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    // This is the preferred method to reobfuscate your jar file
    finalizedBy 'reobfJar'
}

mixin {
    //指定refmap.json文件生成位置
    add sourceSets.main, "endless.refmap.json"
    config "endless.mixins.json"
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
