org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
jei_version=15.2.0.27
jade_id=4986594
ra_id=6418092
bot_ver=448-FORGE
patchouli_ver=84.1-FORGE
curios_ver=5.14.1+1.20.1
bloodmagic_id=5290993
enchanted_id=6530724
de_id=6065044
curios_id=6418456
crt_id=6256146
mixin_version=0.8.5

mapping_channel=official
mapping_version=1.20.1
mod_id=endless
mod_name=Endless
mod_license=MIT
mod_version=1.20.1-0.1-B6
mod_group_id=com.yuo
mod_authors=yuo
mod_description=Endless 1.20.1.