org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
jei_version=15.20.0.115
jade_id=4986594
ra_id=7044775
pe_id=4901949
bot_ver=448-FORGE
patchouli_ver=84.1-FORGE
bloodmagic_id=5290993
enchanted_id=6530724
de_id=6065044
curios_id=6418456
crt_id=6256146
mixin_version=0.8.5
ccl_id=5753868
bc_id=5422013
mmmm_id=6860192
iaf_id=5633453
create_id=6641603
thermal_id=5443583
tc3_id=6777068
flywheel_id=1.0.5-beta
thermal_core_version=11.0.7
mantle_id=6819217
citadel_id=6702068
cofh_core_id=5374122
ye_id=7108732
ae2_id=7096071
ttf_id=5468648
sb_re_id=7073488
croparia_id=5239328
rs_id=4844585
guideme_id=7013686
thermal_c_id=5372746
tlm_id=7510714
cc_api_ver=11.1.136
spacearms_id=7903907
kfd_id=7971499

mapping_channel=official
mapping_version=1.20.1
mod_id=endless
mod_name=Endless
mod_license=MIT
mod_version=1.20.1-0.7.4
mod_group_id=com.yuo
mod_authors=yuo
mod_description=Endless 1.20.1.