pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url 'https://maven.aliyun.com/repository/public/' //阿里云仓库
        }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin/' }
        maven { url 'https://maven.aliyun.com/repository/forge/' }
        maven { url = "https://maven.minecraftforge.net/" }
//        maven { url = "https://maven.parchmentmc.org" }
//        maven { url = "https://repo.spongepowered.org/repository/maven-public/" }
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}